### ISSUE TITLE
Problems installing gem

### ISSUE THREAD

**Issue by strobejb** [turboladen/playful#2]
When using "bundle install":

/upnp.gemspec:17:in ``': No such file or directory -

Lines 17-19 of upnp.gemspec appear to use a non-ascii quote characters. Not sure if this is a unix vs windows thing... changing these quotes to the normal single-quote character fixed the install problem.

On a related note, I used to be able to install this project using the 'specific_install' gem:

i.e.
gem install specific_install
gem specific_install -l git://github.com/turboladen/upnp.git

This worked OK on one PC. When I tried to do the same on another system I get the following error:

git installing from git://github.com/turboladen/upnp.git
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

Probably a gem mis-match between my two systems. But, I was unable to figure out what the problem was, so I used bundle install instead

thanks, for a great project!

**Comment by turboladen** [comment]
Thanks for the report!

So those quotes on lines 17-19... I'm guessing you're talking about the double quotes around the newline chars (as opposed to the backticks)?  If I change those to single quotes on my box, then do a `rake build` (to build the gem package), the #split call doesn't work quite right; I get: 

```
rake aborted!
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    [".gemtest
.gitignore
.infinity_test
.rspec
Gemfile
Gemfile.lock
History.rdoc
README.rdoc
Rakefile
example/test_device.rb
examples/control_point_example.rb
features/control_point.feature
features/device.feature
features/device_discovery.feature
features/step_definitions/control_point_steps.rb
features/step_definitions/device_discovery_steps.rb
features/step_definitions/device_steps.rb
features/support/common.rb
features/support/env.rb
features/support/fake_upnp_device_collection.rb
features/support/world_extensions.rb
lib/core_ext/socket_patch.rb
lib/core_ext/to_upnp_s.rb
lib/upnp.rb
lib/upnp/control_point.rb
lib/upnp/control_point/base.rb
lib/upnp/control_point/device.rb
lib/upnp/control_point/error.rb
lib/upnp/control_point/service.rb
lib/upnp/device.rb
lib/upnp/ssdp.rb
lib/upnp/ssdp/broadcast_searcher.rb
lib/upnp/ssdp/error.rb
lib/upnp/ssdp/legacy/advertisement.rb
lib/upnp/ssdp/legacy/notification.rb
lib/upnp/ssdp/legacy/response.rb
lib/upnp/ssdp/legacy/search.rb
lib/upnp/ssdp/listener.rb
lib/upnp/ssdp/multicast_connection.rb
lib/upnp/ssdp/network_constants.rb
lib/upnp/ssdp/notifier.rb
lib/upnp/ssdp/searcher.rb
lib/upnp/ssdp/version.rb
lib/upnp/version.rb
spec/core_ext/to_upnp_s_spec.rb
spec/spec_helper.rb
spec/support/search_responses.rb
spec/upnp/control_point_spec.rb
spec/upnp/device_spec.rb
spec/upnp/ssdp/multicast_connection_spec.rb
spec/upnp/ssdp/searcher_spec.rb
spec/upnp/ssdp_spec.rb
tasks/control_point.html
tasks/control_point.thor
tasks/search.thor
tasks/test_js/FABridge.js
tasks/test_js/WebSocketMain.swf
tasks/test_js/swfobject.js
tasks/test_js/web_socket.js
test.rb
test/test_ssdp.rb
test/test_ssdp_notification.rb
test/test_ssdp_response.rb
test/test_ssdp_search.rb
test_control_point.rb
test_device.rb
test_listener.rb
upnp.gemspec
", "features/control_point.feature
features/device.feature
features/device_discovery.feature
features/step_definitions/control_point_steps.rb
features/step_definitions/device_discovery_steps.rb
features/step_definitions/device_steps.rb
features/support/common.rb
features/support/env.rb
features/support/fake_upnp_device_collection.rb
features/support/world_extensions.rb
spec/core_ext/to_upnp_s_spec.rb
spec/spec_helper.rb
spec/support/search_responses.rb
spec/upnp/control_point_spec.rb
spec/upnp/device_spec.rb
spec/upnp/ssdp/multicast_connection_spec.rb
spec/upnp/ssdp/searcher_spec.rb
spec/upnp/ssdp_spec.rb
"] are not files
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:2029:in `validate'
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/builder.rb:37:in `build'
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/commands/build_command.rb:29:in `execute'
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/command.rb:278:in `invoke'
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/command_manager.rb:147:in `process_args'
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/command_manager.rb:117:in `run'
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/gem_runner.rb:65:in `run'
    /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p194/bin/gem:25:in `<main>'

Tasks: TOP => build
(See full trace by running task with --trace)
```

Is it possible that you may be running in to this problem: http://stackoverflow.com/questions/9793806/no-such-file-or-directory-git-ls-files-windows ?  I don't have a Windows box handy to check this at the moment, but the `bundle install` works ok on my OSX and Linux boxes, and I believe was running on Windows last week, but I'd have to double check on that when I get back to work tomorrow.

I'd never heard of specific_install--that's pretty cool!  I tried it out on my OSX box and it seemed to work alright:

```
[Steveloveless@sloveless-mbp:upnp(master)]$ gem specific_install -l git://github.com/turboladen/upnp.git
git installing from git://github.com/turboladen/upnp.git
Cloning into '/var/folders/tg/j9jxvvfs4qn9cg4vztzyy2gc0000gp/T/d20120923-11639-11u8red'...
remote: Counting objects: 882, done.
remote: Compressing objects: 100% (434/434), done.
remote: Total 882 (delta 537), reused 762 (delta 417)
Receiving objects: 100% (882/882), 149.07 KiB | 239 KiB/s, done.
Resolving deltas: 100% (537/537), done.
  Successfully built RubyGem
  Name: upnp
  Version: 0.0.1
  File: upnp-0.0.1.gem
Successfully installed upnp-0.0.1
1 gem installed successfully installed

```

...so I'm not quite sure what to say here.  If you find out any more info, let me know--I'd be glad to fix this stuff up.

**Comment by strobejb** [comment]
hi,
thanks for responding so fast. Yes, you are right - my git install was broken - I did a clean install and everything worked. Sorry to waste your time!

cheers
james

**Comment by turboladen** [comment]
No prob!

Also, I'm tidying up some docs, now that I know someone actually might be reading them.  :)
